// +build !ignore_autogenerated

/*


Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecretKeySelector) DeepCopyInto(out *SecretKeySelector) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecretKeySelector.
func (in *SecretKeySelector) DeepCopy() *SecretKeySelector {
	if in == nil {
		return nil
	}
	out := new(SecretKeySelector)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SectigoIssuer) DeepCopyInto(out *SectigoIssuer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SectigoIssuer.
func (in *SectigoIssuer) DeepCopy() *SectigoIssuer {
	if in == nil {
		return nil
	}
	out := new(SectigoIssuer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SectigoIssuer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SectigoIssuerCondition) DeepCopyInto(out *SectigoIssuerCondition) {
	*out = *in
	if in.LastTransitionTime != nil {
		in, out := &in.LastTransitionTime, &out.LastTransitionTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SectigoIssuerCondition.
func (in *SectigoIssuerCondition) DeepCopy() *SectigoIssuerCondition {
	if in == nil {
		return nil
	}
	out := new(SectigoIssuerCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SectigoIssuerList) DeepCopyInto(out *SectigoIssuerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SectigoIssuer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SectigoIssuerList.
func (in *SectigoIssuerList) DeepCopy() *SectigoIssuerList {
	if in == nil {
		return nil
	}
	out := new(SectigoIssuerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SectigoIssuerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SectigoIssuerSpec) DeepCopyInto(out *SectigoIssuerSpec) {
	*out = *in
	out.Provisioner = in.Provisioner
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SectigoIssuerSpec.
func (in *SectigoIssuerSpec) DeepCopy() *SectigoIssuerSpec {
	if in == nil {
		return nil
	}
	out := new(SectigoIssuerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SectigoIssuerStatus) DeepCopyInto(out *SectigoIssuerStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]SectigoIssuerCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SectigoIssuerStatus.
func (in *SectigoIssuerStatus) DeepCopy() *SectigoIssuerStatus {
	if in == nil {
		return nil
	}
	out := new(SectigoIssuerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SectigoProvisioner) DeepCopyInto(out *SectigoProvisioner) {
	*out = *in
	out.OrgIDRef = in.OrgIDRef
	out.UsernameRef = in.UsernameRef
	out.PasswordRef = in.PasswordRef
	out.SecretKeyRef = in.SecretKeyRef
	out.ClientCertRef = in.ClientCertRef
	out.ClientCertPrivKeyRef = in.ClientCertPrivKeyRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SectigoProvisioner.
func (in *SectigoProvisioner) DeepCopy() *SectigoProvisioner {
	if in == nil {
		return nil
	}
	out := new(SectigoProvisioner)
	in.DeepCopyInto(out)
	return out
}
